"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Review={id:string;customerName:string;serviceType:string;rating:number;body:string;ownerResponse:string|null;createdAt:number};
const initial={name:"",email:"",serviceType:"rv",rating:5,body:"",company:""};

export function ReviewsSection(){
  const[reviews,setReviews]=useState<Review[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState(initial),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=useCallback(async()=>{try{const response=await fetch("/api/reviews",{cache:"no-store"}),data=await response.json() as {reviews?:Review[]};setReviews(data.reviews??[]);}finally{setLoading(false)}},[]);
  useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[load]);
  const update=(key:string,value:string|number)=>setForm((current)=>({...current,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await response.json() as {error?:string};if(response.ok){setForm(initial);setMessage("Thank you — your review is now posted.");await load()}else setMessage(data.error??"Your review could not be posted.");setBusy(false)}
  return <section className="section reviews" id="reviews"><div className="section-head"><div><p className="eyebrow">Customer feedback</p><h2>Service, in their own words.</h2></div><button className="button outline" onClick={()=>setOpen(!open)}>{open?"Close Review Form":"Write a Review"}</button></div>
    {open&&<form className="review-form" onSubmit={submit}><div className="review-top"><div><p className="eyebrow">Share your experience</p><h3>Write a review</h3></div><div className="stars">{[1,2,3,4,5].map((n)=><button type="button" className={n<=form.rating?"active":""} onClick={()=>update("rating",n)} key={n}>★</button>)}</div></div><div className="form-row"><label>Name shown publicly<input required value={form.name} onChange={(e)=>update("name",e.target.value)}/></label><label>Email kept private<input required type="email" value={form.email} onChange={(e)=>update("email",e.target.value)}/></label></div><label>Service type<select value={form.serviceType} onChange={(e)=>update("serviceType",e.target.value)}><option value="rv">RV service</option><option value="home">Home service</option><option value="other">Other</option></select></label><label>Your review<textarea required minLength={10} maxLength={1200} rows={4} value={form.body} onChange={(e)=>update("body",e.target.value)}/></label><label className="honeypot">Company<input tabIndex={-1} value={form.company} onChange={(e)=>update("company",e.target.value)}/></label>{message&&<p className="notice">{message}</p>}<button className="button copper" disabled={busy}>{busy?"Posting…":"Post Review"}</button></form>}
    <div className="review-grid">{loading?<p>Loading reviews…</p>:reviews.length?reviews.map((r)=><article key={r.id}><div className="rating">{"★".repeat(r.rating)}<span>{"★".repeat(5-r.rating)}</span></div><blockquote>“{r.body}”</blockquote><p><strong>{r.customerName}</strong><small>{r.serviceType==="rv"?"RV service":r.serviceType==="home"?"Home service":"Other service"}</small></p>{r.ownerResponse&&<div className="owner-response"><small>Response from Anchor Point One</small><p>{r.ownerResponse}</p></div>}</article>):<div className="empty"><h3>Every great business starts with its first review.</h3><p>We&apos;d be honored if yours was one of them.</p><button onClick={()=>setOpen(true)}>Write the First Review</button></div>}</div>
  </section>
}
